### ISSUE TITLE
The Compose file './docker-compose.yml' is invalid 

### ISSUE THREAD

**Issue by nodecentral** [Skyleiger/email-to-paperless#16]
Hi @Skyleiger 

I’m getting the following error, any ideas ?

````
The Compose file './docker-compose.yml' is invalid because: services.email-to-paperless.environment contains {"DB_URL": "jdbc:mariadb://database:3306/email-to-paperless"}, which is an invalid type, it should be a string services.database.environment contains {"MYSQL_DATABASE": "email-to-paperless"}, which is an invalid type, it should be a string
````
Here is my compose file.
````
version: "3.9"
services:
  email-to-paperless:
    image: ghcr.io/skyleiger/email-to-paperless:latest
    restart: always
    volumes:
      - /share/Container/email-to-paperless_logs:/email-to-paperless/logs
    networks:
      - database_network
    environment:
      - DB_URL: jdbc:mariadb://database:3306/email-to-paperless
      - DB_NAME: email-to-paperless
      - DB_USER: email-to-paperless
      - DB_PASSWORD: Tester3456
      - IMAP_URL: imap-mail.outlook.com
      - IMAP_USERNAME: my_email_uk@hotmail.co.uk
      - IMAP_PASSWORD: outlookpassword!
      - PAPERLESS_URL: 192.168.1.234:8777
      - PAPERLESS_TOKEN: cd5d3b9d0f870c3b565tdd450c2cab57d802f37593d
      - IMAP_INCLUDED_FOLDERS: " Travel Tips"
      - PAPERLESS_TAGS: 
      - EMAIL_UPDATE_INTERVAL: 240
      - EMAIL_STORING_STRATEGY: FOLDER
      - EMAIL_STORING_FOLDER: /usr/share/paperless/consume
    #env_file:
    #  - .env
  database:
    image: mariadb:latest
    restart: always
    volumes:
      - email-to-paperless_db:/var/lib/mysql
    networks:
      - database_network
    environment:
      - MYSQL_DATABASE: email-to-paperless
      - MYSQL_USER: email-to-paperless
      - MYSQL_ROOT_PASSWORD: tester2
      - MYSQL_PASSWORD: tester2
volumes:
  email-to-paperless_logs:
  email-to-paperless_db:
networks:
	database_network:

**Comment by Skyleiger** [comment]
Hi,

your `docker-compose.yml` file is invalid. I have corrected it.

```
version: "3.9"
services:
  email-to-paperless:
    image: ghcr.io/skyleiger/email-to-paperless:latest
    restart: always
    volumes:
      - /share/Container/email-to-paperless_logs:/email-to-paperless/logs
    networks:
      - database_network
    environment:
      - DB_URL=jdbc:mariadb://database:3306/email-to-paperless
      - DB_NAME=email-to-paperless
      - DB_USER=email-to-paperless
      - DB_PASSWORD=Tester3456
      - IMAP_URL=imap-mail.outlook.com
      - IMAP_USERNAME=my_email_uk@hotmail.co.uk
      - IMAP_PASSWORD=outlookpassword!
      - PAPERLESS_URL=192.168.1.234:8777
      - PAPERLESS_TOKEN=cd5d3b9d0f870c3b565tdd450c2cab57d802f37593d
      - IMAP_INCLUDED_FOLDERS=" Travel Tips"
      - EMAIL_UPDATE_INTERVAL=240
      - EMAIL_STORING_STRATEGY=FOLDER
      - EMAIL_STORING_FOLDER=/usr/share/paperless/consume
  database:
    image: mariadb:latest
    restart: always
    volumes:
      - email-to-paperless_db:/var/lib/mysql
    networks:
      - database_network
    environment:
      - MYSQL_DATABASE=email-to-paperless
      - MYSQL_USER=email-to-paperless
      - MYSQL_ROOT_PASSWORD=tester2
      - MYSQL_PASSWORD=tester2

volumes:
  email-to-paperless_logs:
  email-to-paperless_db:
networks:
  database_network:
```
